config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get 'allusers', to: 'users#show'

  devise_for :users

  namespace :public, path: nil do
    get :about_us
  end

  resources :questions do
    resources :answers
  end

  root controller: :public, action: :index

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_one :genre
end

app/models/genre.rb
class Genre < ActiveRecord::Base 

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_one :answer, dependent: :destroy

  validates :body, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :answers
  has_many :questions
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(question_id)
    @answer = @question.create_answer(answer_params)
    # guard clause
    return unless @answer.save
    redirect_to question_path(@question)
  end

  def new
    @question = Question.find(question_id)
  end

  def update
    @question = Question.find(question_id)
    @answer = @question.answer
    if @answer.update(answer_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def question_id
    params[:question_id].to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/public_controller.rb
# serves static pages that do not require a log in
class PublicController < ApplicationController
  def index
  end

  def about_us
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(question_id)
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(question_id)
  end

  def create
    @question = Question.new(question_params)
    # binding.pry
    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(question_id)
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(question_id)
    @question.destroy

    redirect_to questions_path
  end

  private

  def question_id
    params[:id].to_i
  end

  def question_params
    params.require(:question).permit(:body, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.haml
- @answer = Answer.new(body: "")
= simple_form_for [@question, @answer] do |f|
  = f.input :body
  = f.button :submit, 'Save'

app/views/answers/edit.html.haml
= form_for @answer, url: answer_path do |f|
  %p
    = f.label :answer
    %br/
    = f.text_area :body
  %p
    = f.submit :Submit, class: 'btn btn-success'

app/views/answers/new.html.haml
= render 'form'

/ %h1 New Answer
/ = bootstrap_form_for [@question, :answer] do |f|
/   %p
/     = f.text_field :body
/   %p
/     = f.submit

app/views/answers/show.html.haml
%p= @question.answer.body

app/views/layouts/_footer.html.haml
%footer
  .container
    .row
      .col-md-6.col-md-offset-3.text-center
        %hr.invisible
        %hr.invisible
        %hr.invisible
        %h4
          = link_to root_path do 
            Forum App
          | &copy; 2016

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: "navbar-brand float-left" do
        Forum App
    #navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to "Hi, #{current_user.email}"
          %li= link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Signin", new_user_session_path
          %li= link_to "Signup", new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Forum App"
    / = favicon_link_tag "favicon.ico"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = javascript_include_tag "application"
    = stylesheet_link_tag "application", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)
    %body
    .wrapper
      = render "layouts/navbar"
      .container.content
        .row
          .col-md-10.col-md-offset-1
            = yield
    = render "layouts/footer"

app/views/questions/_form.html.haml
- if user_signed_in?
  = simple_form_for @question do |f|
    = f.hidden_field :user_id, value: current_user.id
    = f.input :body
    = f.button :submit, 'Save'
- else
  Please
  = link_to "Signin", new_user_session_path
  to create a new Question

app/views/questions/edit.html.haml
%h1 Edit Question

= render 'form'

app/views/questions/index.html.haml
%h1 Questions
%br
= link_to new_question_path, class: 'btn btn-primary' do
  .glyphicon.glyphicon-plus
  Create
%hr.invisible
%table.table.table-striped
  %tr
    %th Question
    %th Answer
    %th Username
    %th
  - @questions.each do |question|
    %tr
      %td= link_to question.body, question
      - if question.answer
        %td= question.answer.body
      - else
        %td Unanswered Question
      - if question.user.email
        %td= question.user.email
      - else
        %td 'No namer'

app/views/questions/new.html.haml
%h1 New Question

= render 'form'

app/views/questions/show.html.haml
%p
  %h2 Question
  %p= @question.body
%br
  - if user_signed_in?
    = link_to 'Edit the question', edit_question_path(@question)

%h2 Answer
- if @question.answer
  %p= @question.answer.body

- if user_signed_in?
  %h2 Add to this answer
  - if @question.answer
    = simple_form_for([@question, @question.answer]) do |f|
      = f.input :body
      = f.button :submit, 'Save'
  - else
    Be the first to begin answering this question!
    %br
    = link_to new_question_answer_path(@question), class: 'btn btn-primary' do
      .glyphicon.glyphicon-plus
      Create

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.haml
- @users.each do |user|
  = user.email
  = user.encrypted_password
  .br